language: java

script:
   - mvn clean install 

   
after_success:
  - bash <(curl -s https://codecov.io/bash)
   
after_failure:
  - cat /home/travis/build/Bonjouravous/Dispenser/target/surefire-reports/*.txt
